### ISSUE TITLE
Add clarification on sudo: true

### ISSUE THREAD

**Issue by cancan101** [moul/travis-docker#22]
The advanced example shows `sudo: true` but the simple example does not. Is `sudo: true` required for this to work?

**Comment by gagern** [comment]
I'm just a visitor, not even a user (yet). But I know that Travis apparently runs new projects on [their new infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/) _unless_ they specify `sudo:true`. On the other hand, existing projects aparently continue on the old infrastructure _unless_ the opt-in using `sudo:false`. Since travis-docker uses sudo (does it have to be that way?), it has to run on the old infrastructure, and thus the configuration setting at least doesn't hurt, and might even be required for new projects.

**Comment by cancan101** [comment]
I agree, it looks like sudo [is required](https://github.com/moul/travis-docker/blob/1b0c31bb11d1dd14a9b17becbfef485b9949586e/run#L26) but that fact is not clear from the RAEDME.

**Comment by moul** [comment]
Yes, you're right, do you want to open a PR ?

**Comment by gagern** [comment]
Created #23. And I'd still like to know whether the `sudo` requirement could be avoided. From what I read about user-mode linux, it should be possible to make it run with normal user privileges. Should I open a new issue asking about this as a feature?

**Comment by moul** [comment]
@gagern, yes you can open a new issue, I will try to play with a full user-mode version with /var/lib/docker in /home etc
